/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color System from Stitch
        'tertiary-container': '#c04400',
        'surface-dim': '#d9d9e5',
        'inverse-primary': '#b4c5ff',
        'surface-tint': '#0053db',
        'secondary-container': '#7cf994',
        'inverse-on-surface': '#f0f0fb',
        'tertiary-fixed': '#ffdbce',
        'outline': '#737686',
        'surface-variant': '#e1e2ed',
        'on-tertiary-container': '#ffede7',
        'on-secondary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#7f2b00',
        'on-primary-fixed-variant': '#003ea8',
        'background': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#00174b',
        'inverse-surface': '#2e3039',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'surface-container': '#ededf9',
        'on-background': '#191b23',
        'surface-container-high': '#e7e7f3',
        'outline-variant': '#c3c6d7',
        'surface-bright': '#faf8ff',
        'primary-container': '#2563eb',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#370e00',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f3f3fe',
        'on-surface-variant': '#434655',
        'on-error': '#ffffff',
        'secondary-fixed': '#7ffc97',
        'surface': '#faf8ff',
        'primary-fixed': '#dbe1ff',
        'on-primary-container': '#eeefff',
        'secondary-fixed-dim': '#62df7d',
        'surface-container-highest': '#e1e2ed',
        'tertiary': '#973400',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#b4c5ff',
        'on-surface': '#191b23',
        'on-secondary-container': '#007230',
        'on-secondary': '#ffffff',
        'primary': '#004ac6',
        'on-secondary-fixed-variant': '#005320',
        'secondary': '#006e2d',
        'tertiary-fixed-dim': '#ffb599',
        // Legacy compatibility
        blue: {
          600: '#2563eb',
          700: '#004ac6',
        },
        green: {
          600: '#006e2d',
        },
        red: {
          600: '#ba1a1a',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'gutter': '20px',
        'container-max': '1200px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        'soft': '0 2px 8px rgba(0, 0, 0, 0.08)',
        'medium': '0 4px 12px rgba(0, 0, 0, 0.12)',
        'hard': '0 8px 24px rgba(0, 0, 0, 0.16)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-down': 'slideDown 0.4s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
